cleanup

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -6,9 +6,9 @@
 #
 # Provison on default 'sites'
 # E.g ./deploy.sh reload history
-# 
-# Provision on drush 
-# E.g ./deploy.sh reload history-ssh drush 
+#
+# Provision on drush
+# E.g ./deploy.sh reload history-ssh drush
 #
 # Command arguments
 
@@ -74,18 +74,18 @@ function restart {
 
 # Main
 case $cmd in
-    reload|destroy|restart|start|stop)
-        [[ -z ${service} ]] && echo "service name is required" && exit 1
-        ;;
-    help)
-        echo "deploy.sh reload|destroy|restart|stop|start <service> [role]"
-        exit 0
-        ;;
-       *)
-        echo "Unknown command: $cmd";
-        echo "deploy.sh reload|destroy|restart|stop|start <service> [role]"
-        exit 1
-        ;;
+  reload|destroy|restart|start|stop)
+    [[ -z ${service} ]] && echo "service name is required" && exit 1
+    ;;
+  help)
+    echo "deploy.sh reload|destroy|restart|stop|start <service> [role]"
+    exit 0
+    ;;
+  *)
+    echo "Unknown command: $cmd";
+    echo "deploy.sh reload|destroy|restart|stop|start <service> [role]"
+    exit 1
+    ;;
 esac
 
 
@@ -93,7 +93,7 @@ esac
 sitedir=/var/lib/apps/sites/${service}/units
 [[ ! -d ${sitedir} ]] && sitedir=${PWD}
 
-# If image is given, pull the image first 
+# If image is given, pull the image first
 [[ -n ${image} ]] && docker pull ${image}
 
 # manage SSH units first
@@ -127,7 +127,7 @@ if [[ ${role:-'sites'} = 'sites' ]]; then
       unset old_unit
       unset unit
     done
-  
+
     # clean up any remaining old units
     for u in ${services[*]}; do
       fleetctl destroy ${u}
diff --git a/bin/email b/bin/email
--- a/bin/email
+++ b/bin/email
@@ -1,31 +1,30 @@
 #!/bin/bash
 
-while getopts ":f:t:s:m:" OPTION
-do
-    case $OPTION in
-        f)
-          FROM=$OPTARG
-          ;;
-        t)
-          TO=$OPTARG
-          ;;
-        s)
-          SUBJECT=$OPTARG
-          ;;
-        m)
-          MESSAGE=$OPTARG
-          ;;
-        ?)
-          echo "$0 -f <from> -t <rcpt1@example.com,rcpt2@example.com> -s <subject> -m </path/to/message-file>"
-          exit
-          ;;
-    esac
+while getopts ":f:t:s:m:" OPTION; do
+  case $OPTION in
+    f)
+      FROM=$OPTARG
+      ;;
+    t)
+      TO=$OPTARG
+      ;;
+    s)
+      SUBJECT=$OPTARG
+      ;;
+    m)
+      MESSAGE=$OPTARG
+      ;;
+    ?)
+      echo "$0 -f <from> -t <rcpt1@example.com,rcpt2@example.com> -s <subject> -m </path/to/message-file>"
+      exit
+      ;;
+  esac
 done
 
 if [[ ! $FROM || ! $TO || ! $SUBJECT || ! -f $MESSAGE ]]; then
-    echo "FROM, TO, SUBJECT or message file are missing."
-     echo "$0 -f <from> -t \"<rcpt1@example.com,rcpt2@example.com>\" -s \"<subject>\" -m </path/to/message-file>"
-    exit 1
+  echo "FROM, TO, SUBJECT or message file are missing."
+  echo "$0 -f <from> -t \"<rcpt1@example.com,rcpt2@example.com>\" -s \"<subject>\" -m </path/to/message-file>"
+  exit 1
 fi
 
 docker run -e FROM="$FROM" -e TO="$TO" -e SUBJECT="$SUBJECT" -v $MESSAGE:/tmp/message.txt -v /home/core/.aws:/root/.aws suet/aws-ses
